#!/usr/bin/env python3
"""Generates app/src/main/kotlin/com/telenebula/app/ui/icons/TnIcons.kt from lucide SVGs.

The vocabulary below is the RN app's fragments/Icon.tsx mapping (app name -> lucide icon).
Run: python3 scripts/gen-icons.py   (needs network; pins the lucide-static version below)
"""
import re, sys, urllib.request, xml.etree.ElementTree as ET
from pathlib import Path

LUCIDE_VERSION = "0.545.0"
ICONS = {
    "search": "search", "close": "x", "pencil": "pencil", "plus": "plus", "person_add": "user-plus",
    "chats": "message-circle", "contacts": "circle-user-round", "settings": "settings", "person": "user",
    "account": "circle-user-round", "back": "arrow-left", "call": "phone", "call_end": "phone-off",
    "call_in": "phone-incoming", "call_out": "phone-outgoing", "call_missed": "phone-missed", "video": "video",
    "video_off": "video-off", "flip_camera": "switch-camera", "menu": "ellipsis-vertical", "send": "send",
    "attach": "paperclip", "emoji": "smile", "mic": "mic", "mic_off": "mic-off", "speaker": "volume-2",
    "lock": "lock", "trash": "trash-2", "clear": "eraser", "certificate": "file-text", "shield": "shield-check",
    "qr": "qr-code", "scan": "scan-line", "retry": "refresh-cw", "copy": "copy", "forward": "corner-up-right",
    "reply": "corner-up-left", "image": "image", "folder": "folder", "play": "play", "file": "file", "list": "list",
    "check": "check", "eye": "eye", "clock": "clock-3", "hourglass": "hourglass", "info": "info", "circle": "circle",
    "minimize": "chevron-down", "chevron_down": "chevron-down", "chevron_right": "chevron-right", "link": "link",
    "pin": "pin", "pin_off": "pin-off", "archive": "archive", "unarchive": "archive-restore", "bell": "bell",
    "bell_off": "bell-off", "block": "ban", "mark_unread": "mail-open", "vibrate": "vibrate",
    "ping": "satellite-dish", "desktop": "monitor", "square_plus": "square-plus", "pause": "pause",
}
NS = "{http://www.w3.org/2000/svg}"

def fetch(name):
    url = f"https://cdn.jsdelivr.net/npm/lucide-static@{LUCIDE_VERSION}/icons/{name}.svg"
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read().decode()

def f(v):  # compact float
    s = f"{float(v):.3f}".rstrip("0").rstrip(".")
    return s if s not in ("", "-0") else "0"

def to_paths(svg):
    root = ET.fromstring(svg)
    out = []
    for el in root.iter():
        tag = el.tag.replace(NS, "")
        a = el.attrib
        if tag == "path":
            out.append(a["d"])
        elif tag == "circle":
            cx, cy, r = float(a["cx"]), float(a["cy"]), float(a["r"])
            out.append(f"M{f(cx-r)} {f(cy)}a{f(r)} {f(r)} 0 1 0 {f(2*r)} 0a{f(r)} {f(r)} 0 1 0 {f(-2*r)} 0")
        elif tag == "line":
            out.append(f"M{f(a['x1'])} {f(a['y1'])}L{f(a['x2'])} {f(a['y2'])}")
        elif tag in ("polyline", "polygon"):
            pts = re.findall(r"[-\d.]+", a["points"])
            pairs = list(zip(pts[0::2], pts[1::2]))
            d = "M" + " L".join(f"{f(x)} {f(y)}" for x, y in pairs)
            out.append(d + ("Z" if tag == "polygon" else ""))
        elif tag == "rect":
            x, y, w, h = (float(a.get(k, 0)) for k in ("x", "y", "width", "height"))
            rx = float(a.get("rx", a.get("ry", 0)))
            if rx == 0:
                out.append(f"M{f(x)} {f(y)}h{f(w)}v{f(h)}h{f(-w)}Z")
            else:
                out.append(f"M{f(x+rx)} {f(y)}h{f(w-2*rx)}a{f(rx)} {f(rx)} 0 0 1 {f(rx)} {f(rx)}v{f(h-2*rx)}a{f(rx)} {f(rx)} 0 0 1 {f(-rx)} {f(rx)}h{f(-(w-2*rx))}a{f(rx)} {f(rx)} 0 0 1 {f(-rx)} {f(-rx)}v{f(-(h-2*rx))}a{f(rx)} {f(rx)} 0 0 1 {f(rx)} {f(-rx)}Z")
    return out

def main():
    dest = Path(__file__).resolve().parent.parent / "app/src/main/kotlin/com/telenebula/app/ui/icons/TnIcons.kt"
    entries = []
    for app_name, lucide in ICONS.items():
        paths = to_paths(fetch(lucide))
        entries.append((app_name, lucide, paths))
        print(f"{app_name:14} <- {lucide} ({len(paths)} paths)", file=sys.stderr)
    lines = [
        "// GENERATED by scripts/gen-icons.py from lucide-static " + LUCIDE_VERSION + " — do not edit.",
        "package com.telenebula.app.ui.icons", "",
        "import androidx.compose.ui.graphics.Color",
        "import androidx.compose.ui.graphics.SolidColor",
        "import androidx.compose.ui.graphics.StrokeCap",
        "import androidx.compose.ui.graphics.StrokeJoin",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "import androidx.compose.ui.graphics.vector.addPathNodes",
        "import androidx.compose.ui.unit.dp", "",
        "/** The app's icon vocabulary; names mirror the RN `IconName` union. */",
        "enum class TnIcon(internal val lucideName: String) {",
    ]
    lines += [f"    {n.upper()}(\"{l}\")," for n, l, _ in entries]
    lines += ["}", "",
        "/** Lucide icons as ImageVectors: 24-unit grid, 2-unit round stroke, no fill. Built once, on first use. */",
        "internal object TnIconVectors {",
        "    private val cache = arrayOfNulls<ImageVector>(TnIcon.entries.size)", "",
        "    fun get(icon: TnIcon): ImageVector = cache[icon.ordinal] ?: build(icon).also { cache[icon.ordinal] = it }", "",
        "    private fun build(icon: TnIcon): ImageVector = ImageVector.Builder(",
        "        name = icon.lucideName, defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f,",
        "    ).apply {",
        "        for (d in PATHS[icon.ordinal]) addPath(",
        "            pathData = addPathNodes(d), fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f,",
        "            strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round,",
        "        )",
        "    }.build()", "",
        "    private val PATHS: Array<Array<String>> = arrayOf(",
    ]
    for n, l, paths in entries:
        joined = ", ".join('"' + p.replace('"', '\\"') + '"' for p in paths)
        lines.append(f"        arrayOf({joined}), // {n}")
    lines += ["    )", "}", ""]
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines))
    print(f"wrote {dest}", file=sys.stderr)

if __name__ == "__main__":
    main()
